// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    XAutocomplete: typeof import('@/components/ts')['Autocomplete']
    XInput: typeof import('@/components/ts')['Input']
    XList: typeof import('@/components/ts')['List']
    XSearchInput: typeof import('@/components/ts')['SearchInput']
    XTable: typeof import('@/components/ts')['Table']
    XTcell: typeof import('@/components/ts')['Tcell']
    XTd: typeof import('@/components/ts')['Td']
    XTh: typeof import('@/components/ts')['Th']
    XThead: typeof import('@/components/ts')['Thead']
    XTr: typeof import('@/components/ts')['Tr']
  }
}

export { }
