export let inputProps = () => {
  return {
    flexed: Boolean,
    container: String,
    grid: Boolean,
    static: Boolean,
    form: Object,
    dtf: Boolean,
    formKeys: Object,
    url: String,
    query: Object,
    centerGrid: Boolean,
    uppercase: Boolean,
    flat: Boolean,
    dark: Boolean,
    password: Boolean,
    value: {},
    items: Array,
    name: String,
    light: Boolean,
    mask: [String, Object],
    //   model: String,
    pilot: Boolean,
    id: String,
    itemText: { type: [String], default: null },
    itemValue: [String],
    type: { default: "text" },
    format: Function,
    onSelect: Function,
    combobox: Boolean,
    select: Boolean,
    autoComplete: Boolean,
    rounded: Boolean,
    menu: Boolean,
    textarea: Boolean,
    caps: Boolean,
    linputClass: String,
    suggest: Boolean,
    multiple: Boolean,
    loading: Boolean,
    plain: Boolean,
    col: {
      type: [String],
    },
    selection: {
      type: [Number],
      default: 1,
    },
    modelValue: {
      type: [String, Object, Number],
      default: "",
    },
    centerText: Boolean,
    tile: Boolean,
    readonly: Boolean,
    valueFormat: Function,
    disabled: Boolean,
    // geo: Object as PropType<IGeo>,
    dense: Boolean,
    clearable: Boolean,
    prependIcon: String,
    placeholder: String,
    maxlength: Number,
    prependInnerIcon: String,
    prefix: String,
    suffix: String,
    hint: String,
    appendIcon: String,
    appendInnerIcon: String,
    label: String,
    source: String,
    custom: Boolean,
    addOn: Boolean,
  };
};
